project_id = "cqtavgzldzgdprcigotc"

[functions.redeem-invite]
verify_jwt = true

[functions.get-scripts]
verify_jwt = true

[functions.get-script]
verify_jwt = true

[functions.set-profile-name]
verify_jwt = true

[functions.sync-leaderboard]
verify_jwt = true

[functions.admin-dashboard]
verify_jwt = true

[functions.admin-create-invite]
verify_jwt = true
