import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createCipheriv, createHash, randomBytes } from 'node:crypto';
import { dirname, join } from 'node:path';

const root = new URL('..', import.meta.url);
const manifestPath = new URL('../private/scripts/scripts.json', import.meta.url);
const outputPath = new URL('../supabase/seed/encrypted_scripts.sql', import.meta.url);
const outputJsonPath = new URL('../supabase/seed/encrypted_scripts.json', import.meta.url);

function sql(value){
  if(value == null) return 'null';
  return `'${String(value).replaceAll("'", "''")}'`;
}

function encryptJson(jsonText, key){
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  const encrypted = Buffer.concat([cipher.update(jsonText, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return {
    algorithm: 'AES-256-GCM',
    iv: iv.toString('base64'),
    ciphertext: Buffer.concat([encrypted, tag]).toString('base64')
  };
}

async function main(){
  const key = Buffer.from(process.env.SCRIPT_MASTER_KEY || '', 'base64');
  if(key.length !== 32){
    throw new Error('SCRIPT_MASTER_KEY muss ein base64-kodierter 32-Byte-Key sein.');
  }

  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  const scripts = Array.isArray(manifest.scripts) ? manifest.scripts : [];
  const rows = [];
  const jsonRows = [];

  for(const item of scripts){
    const file = item.file || item.src || item.path;
    if(!file) throw new Error(`Skript ${item.id || item.title || 'ohne Namen'} hat keine Datei.`);
    const source = new URL(`../private/scripts/${file}`, import.meta.url);
    const jsonText = await readFile(source, 'utf8');
    const ciphertext = encryptJson(jsonText, key);
    const checksum = createHash('sha256').update(jsonText).digest('hex');
    const id = item.id || file.replace(/\.[^.]+$/, '');
    const title = item.title || item.label || id;
    const label = item.label || title;
    rows.push(`(${sql(id)}, ${sql(title)}, ${sql(label)}, ${sql(JSON.stringify(ciphertext))}::jsonb, ${sql(checksum)})`);
    jsonRows.push({ id, title, label, ciphertext, checksum });
  }

  const sqlText = [
    '-- Generated by tools/encrypt_scripts.mjs. Do not edit by hand.',
    'insert into public.encrypted_scripts(id, title, label, ciphertext, checksum)',
    `values\n${rows.join(',\n')}`,
    'on conflict (id) do update set',
    '  title = excluded.title,',
    '  label = excluded.label,',
    '  ciphertext = excluded.ciphertext,',
    '  checksum = excluded.checksum,',
    '  updated_at = now();',
    ''
  ].join('\n');

  await mkdir(dirname(outputPath.pathname), { recursive: true });
  await writeFile(outputPath, sqlText, 'utf8');
  await writeFile(outputJsonPath, `${JSON.stringify({ scripts: jsonRows }, null, 2)}\n`, 'utf8');
  console.log(`Wrote ${rows.length} encrypted scripts to ${join(root.pathname, 'supabase/seed/encrypted_scripts.sql')}`);
  console.log(`Wrote ${jsonRows.length} encrypted scripts to ${join(root.pathname, 'supabase/seed/encrypted_scripts.json')}`);
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
